version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app_govtech
    ports:
      - "8000:8000"
    # depends_on:
    #   - mongo
    # environment:
    #   - MONGO_URI=mongodb://mongo:27017
    

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    

volumes:
  mongo_data:

networks:
  local_net: