version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app_govtech
    ports:
      - "8000:8000"
    

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    

volumes:
  mongo_data:
